@BASE_URL = http://localhost:3001/api/auth/guest
@TOKEN = 1

#
POST {{BASE_URL}}/register
Content-Type: application/json

{

"role": "guest", 
"firstName": "ram", 
"lastName": "kumar", 
"email": "ram@gmail.com", 
"phone": "1234567891", 
"password": "Ram@123", 
"confirmPassword": "Ram@123", 
"hotelName": "Ram Hotel", 
"hotelAddress":"Rammechhap",
"termsAccepted":"true"
}

###